FROM ruby:3.4-alpine

WORKDIR /app

RUN apk add --no-cache \
  build-base \
  postgresql-dev \
  tzdata \
  yaml-dev \
  pkgconf \
  git

COPY Gemfile Gemfile.lock ./
RUN bundle install

COPY . .

EXPOSE 3000
CMD ["rails", "server", "-b", "0.0.0.0"]
